---
- name: template TEST
  hosts: localhost
  roles:
  connection: local
  gather_facts: no
  tasks:
  - name: 'template'
    template:
      src: hp.j2
      dest: "{{ fname }}_hp_conf.txt"
      lstrip_blocks: yes
