---
version: "11.4R5.5"
system:
  host_name: "HOSTNAME"
  domain_name: "DOMAINNAME"
  time_zone: "Asia/Tokyo"
  root_authentication:
    encrypted_password: "$1$VOBKGUFb$W68QQoEhOg7duVwg.R99Q0"
  login:
    user:
    - name: "user1"
      uid: "2000"
      class: "super-user"
      authentication:
        encrypted_password: "$1$VOBKGUFb$W68QQoEhOg7duVwg.R99Q0"
  services:
    ssh:
      root_login: "deny"
    web_management:
      http:
      https:
        system_generated_certificate:
  syslog:
    user:
      name: "*"
      contents:
      - name: "any"
        emergency:
    file:
    - name: "messages"
      contents:
      - name: "any"
        notice:
      - name: "authorization"
        info:
    - name: "interactive-commands"
      contents:
      - name: "interactive-commands"
        any:
  ntp:
    server:
    - name: "10.5.16.193"
    - name: "10.5.17.193"
      prefer:
    - name: "10.5.18.193"
chassis:
  aggregated_devices:
    ethernet:
      device_count: "1"
interfaces:
  interface_range:
  - name: "IF-RANGE-01"
    member:
    - name: "ge-0/0/0"
    unit:
      name: "0"
      description: "IF-RANGE-01-NAME"
      family:
        ethernet_switching:
          port_mode: "trunk"
          vlan:
            members:
            - name: "VLAN-90-seg"
            - name: "VLAN-91-seg"
            - name: "VLAN-92-seg"
            - name: "VLAN-93"
            - name: "VLAN-94"
            - name: "VLAN-95"
            - name: "VLAN-96"
            - name: "VLAN-97"
            - name: "VLAN-98"
  - name: "IF-RANGE-02"
    member:
    - name: "ge-0/0/2"
    - name: "ge-0/0/3"
    - name: "ge-0/0/4"
    unit:
      name: "0"
      description: "IF-RANGE-02-NAME"
      family:
        ethernet_switching:
          port_mode: "trunk"
          vlan:
            members:
            - name: "VLAN-90-seg"
            - name: "VLAN-91-seg"
            - name: "VLAN-92-seg"
            - name: "VLAN-93"
            - name: "VLAN-94"
            - name: "VLAN-95"
            - name: "VLAN-96"
            - name: "VLAN-97"
            - name: "VLAN-98"
  - name: "IF-RANGE-03"
    member:
    - name: "ge-0/0/5"
    unit:
      name: "0"
      description: "IF-RANGE-03-NAME"
      family:
        ethernet_switching:
          port_mode: "trunk"
          vlan:
            members:
            - name: "VLAN-90-seg"
            - name: "VLAN-91-seg"
            - name: "VLAN-92-seg"
            - name: "VLAN-93"
            - name: "VLAN-94"
            - name: "VLAN-95"
            - name: "VLAN-96"
            - name: "VLAN-97"
            - name: "VLAN-98"
  - name: "IF-RANGE-04"
    member:
    - name: "ge-0/0/6"
    - name: "ge-0/0/7"
    - name: "ge-0/0/8"
    - name: "ge-0/0/10"
    - name: "ge-0/0/17"
    unit:
      name: "0"
      description: "IF-RANGE-04-NAME"
      family:
        ethernet_switching:
          port_mode: "access"
          vlan:
            members:
            - name: "VLAN-90-seg"
  - name: "IF-RANGE-05"
    member:
    - name: "ge-0/0/11"
    - name: "ge-0/0/12"
    - name: "ge-0/0/13"
    - name: "ge-0/0/14"
    unit:
      name: "0"
      description: "IF-RANGE-05-NAME"
      family:
        ethernet_switching:
          port_mode: "access"
          vlan:
            members:
            - name: "VLAN-90-seg"
  - name: "IF-RANGE-06"
    member:
    - name: "ge-0/0/18"
    unit:
      name: "0"
      description: "IF-RANGE-06-NAME"
      family:
        ethernet_switching:
          port_mode: "access"
          vlan:
            members:
            - name: "VLAN-90-seg"
  - name: "IF-RANGE-07"
    member:
    - name: "ge-0/0/19"
    unit:
      name: "0"
      description: "IF-RANGE-07-NAME"
      family:
        ethernet_switching:
          port_mode: "trunk"
          vlan:
            members:
            - name: "VLAN-90-seg"
            - name: "VLAN-92-seg"
  - name: "IF-RANGE-08"
    member:
    - name: "ge-0/0/22"
    - name: "ge-0/0/23"
    - name: "ge-0/0/21"
    unit:
      name: "0"
      description: "Management"
      family:
        ethernet_switching:
          port_mode: "access"
          vlan:
            members:
            - name: "VLAN-92-seg"
  - name: "IF-RANGE-09"
    member:
    - name: "ge-0/0/15"
    - name: "ge-0/0/16"
    description: "IF-RANGE-09-NAME"
    ether_options:
      ieee_802_3ad:
        bundle: "ae0"
  interface:
  - name: "ge-0/0/0"
    unit:
      name: "0"
      description: "IF-GE-0-0-0-NAME"
  - name: "ge-0/0/1"
    disable:
  - name: "ge-0/0/2"
    description: "IF-GE-0-0-2-NAME"
  - name: "ge-0/0/3"
    description: "IF-GE-0-0-3-NAME"
  - name: "ge-0/0/4"
    description: "IF-GE-0-0-4-NAME"
  - name: "ge-0/0/5"
    description: "IF-GE-0-0-5-NAME"
  - name: "ge-0/0/6"
    description: "IF-GE-0-0-6-NAME"
  - name: "ge-0/0/7"
    description: "IF-GE-0-0-7-NAME"
  - name: "ge-0/0/8"
    description: "IF-GE-0-0-8-NAME"
  - name: "ge-0/0/9"
    disable:
  - name: "ge-0/0/10"
    description: "IF-GE-0-0-10-NAME"
  - name: "ge-0/0/11"
    description: "IF-GE-0-0-11-NAME"
  - name: "ge-0/0/12"
    description: "IF-GE-0-0-12-NAME"
  - name: "ge-0/0/13"
    description: "IF-GE-0-0-13-NAME"
  - name: "ge-0/0/14"
    description: "IF-GE-0-0-14-NAME"
  - name: "ge-0/0/15"
    description: "IF-GE-0-0-15-NAME"
  - name: "ge-0/0/16"
    description: "IF-GE-0-0-16-NAME"
  - name: "ge-0/0/17"
    description: "IF-GE-0-0-17-NAME"
  - name: "ge-0/0/18"
    description: "IF-GE-0-0-18-NAME"
  - name: "ge-0/0/19"
    description: "IF-GE-0-0-19-NAME"
  - name: "ge-0/0/20"
    disable:
  - name: "ge-0/0/22"
    description: "IF-GE-0-0-22-NAME"
  - name: "ge-0/0/23"
    description: "IF-GE-0-0-23-NAME"
  - name: "ge-0/1/0"
    disable:
  - name: "ge-0/1/1"
    disable:
  - name: "ge-0/1/2"
    disable:
  - name: "ge-0/1/3"
    disable:
  - name: "ae0"
    description: "IF-AE-0-NAME"
    aggregated_ether_options:
      link_speed: "1g"
      lacp:
        active:
        periodic: "fast"
    unit:
      name: "0"
      family:
        ethernet_switching:
          port_mode: "access"
          vlan:
            members:
            - name: "VLAN-106-seg"
  - name: "me0"
    unit:
      name: "0"
      family:
        inet:
          address:
            name: "10.5.17.238/21"
snmp:
  system_name: "SNMPHOSTNAME"
  location: "LOCATION4"
  contact: "CONTACT"
  interface: "me0.0"
  community:
  - name: "snmpCom"
    authorization: "read-only"
  trap_group:
    name: "snmpCom"
    version: "v2"
    categories:
      authentication:
      chassis:
      link:
      remote_operations:
      routing:
      startup:
      rmon_alarm:
      vrrp_events:
      configuration:
    targets:
    - name: "10.5.17.183"
    - name: "10.5.16.183"
routing_options:
  static:
    route:
    - addr: "10.6.2.0"
      mask: "255.255.255.0"
      next_hop: "10.5.17.250"
    - addr: "10.6.3.0"
      mask: "255.255.255.0"
      next_hop: "10.5.17.250"
    - addr: "10.6.4.0"
      mask: "255.255.255.0"
      next_hop: "10.5.17.250"
    - addr: "10.6.1.0"
      mask: "255.255.255.0"
      next_hop: "10.5.16.250"
protocols:
  mstp:
    disable:
  vstp:
    vlan_group:
      group:
      - name: "EDI-Group1"
        vlan:
        - name: "VLAN-90-seg"
        - name: "VLAN-91-seg"
        - name: "VLAN-92-seg"
        - name: "VLAN-98"
        - name: "VLAN-93"
        - name: "VLAN-94"
        - name: "VLAN-95"
        - name: "VLAN-97"
        - name: "VLAN-96"
        bridge_priority: "32k"
        hello_time: "2"
        interface:
        - name: "ge-0/0/2.0"
          cost: "4"
          mode: "point-to-point"
          bpdu_timeout_action:
            log:
        - name: "ge-0/0/3.0"
          cost: "4"
          mode: "point-to-point"
          bpdu_timeout_action:
            log:
        - name: "ge-0/0/4.0"
          cost: "4"
          mode: "point-to-point"
          bpdu_timeout_action:
            block:
            log:
        - name: "IF-RANGE-01"
          disable:
        - name: "IF-RANGE-03"
          disable:
        - name: "IF-RANGE-04"
          disable:
        - name: "IF-RANGE-05"
          disable:
        - name: "IF-RANGE-06"
          disable:
        - name: "IF-RANGE-07"
          disable:
        - name: "IF-RANGE-08"
          disable:
        - name: "ae0.0"
          disable:
  lldp:
    interface:
      name: "all"
  lldp_med:
    interface:
      name: "all"
ethernet_switching_options:
  port_error_disable:
    disable_timeout: "60"
  storm_control:
    interface:
      name: "all"
vlans:
  vlan:
  - name: "VLAN-106-seg"
    description: "VLAN-106-seg"
    vlan_id: "106"
  - name: "VLAN-90-seg"
    description: "VLAN 90 seg"
    vlan_id: "90"
  - name: "VLAN-91-seg"
    description: "VLAN 91 seg"
    vlan_id: "91"
  - name: "VLAN-92-seg"
    description: "VLAN 92 seg"
    vlan_id: "92"
  - name: "VLAN-93"
    description: "VLAN-93-seg"
    vlan_id: "93"
  - name: "VLAN-94"
    description: "VLAN 94 seg"
    vlan_id: "94"
  - name: "VLAN-95"
    description: "VLAN 95 seg"
    vlan_id: "95"
  - name: "VLAN-96"
    description: "VLAN 96 seg"
    vlan_id: "96"
  - name: "VLAN-97"
    description: "VLAN 97 seg"
    vlan_id: "97"
  - name: "VLAN-98"
    description: "VLAN-98-seg"
    vlan_id: "98"
