---
- name: template TEST
  hosts: localhost
  roles:
  connection: local
  gather_facts: no
  tasks:
  - name: 'template'
    template:
      src: aruba.j2
      dest: "{{ fname }}_aruba_conf.txt"
      lstrip_blocks: yes
